name: Release

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          
      - name: Package
        run: |
          echo packaging...
          tar -czf terraform-s3-${{ env.RELEASE_VERSION }}.tar.gz terraform labfiles

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: terraform-s3-${{ env.RELEASE_VERSION }}
          path: terraform-s3-${{ env.RELEASE_VERSION }}.tar.gz

      - name: Make Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: terraform-s3-${{ env.RELEASE_VERSION }}.tar.gz
          files: |
            terraform-s3-${{ env.RELEASE_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
